use std::collections::{BTreeMap, BTreeSet};

use serde::{Deserialize, Serialize};
use thiserror::Error;
use time::OffsetDateTime;
use uuid::Uuid;

/// Stable identifier generated by the creating device and safe to sync.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct ItemId(pub Uuid);

impl ItemId {
    #[must_use]
    pub const fn from_uuid(value: Uuid) -> Self {
        Self(value)
    }
}

impl std::fmt::Display for ItemId {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.0.fmt(formatter)
    }
}

/// Whole minutes are the persisted scheduling unit. UI precision may be finer,
/// but whole minutes keep plans portable and stable across platforms.
#[derive(Debug, Default, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(transparent)]
pub struct Minutes(pub u32);

impl Minutes {
    pub const ZERO: Self = Self(0);

    #[must_use]
    pub const fn get(self) -> u32 {
        self.0
    }

    #[must_use]
    pub const fn is_zero(self) -> bool {
        self.0 == 0
    }
}

/// A range records estimation uncertainty while `expected` remains the amount
/// the deterministic planner reserves. `remaining` accounts for partial work.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct DurationEstimate {
    pub minimum: Minutes,
    pub expected: Minutes,
    pub maximum: Minutes,
    pub remaining: Option<Minutes>,
    pub source: EstimateSource,
}

impl DurationEstimate {
    #[must_use]
    pub const fn exact(minutes: u32) -> Self {
        let value = Minutes(minutes);
        Self {
            minimum: value,
            expected: value,
            maximum: value,
            remaining: None,
            source: EstimateSource::User,
        }
    }

    #[must_use]
    pub const fn planning_minutes(self) -> Minutes {
        match self.remaining {
            Some(remaining) => remaining,
            None => self.expected,
        }
    }

    pub(crate) fn validate(self) -> Result<(), &'static str> {
        if self.minimum.is_zero() {
            return Err("duration minimum must be greater than zero");
        }
        if self.minimum > self.expected || self.expected > self.maximum {
            return Err("duration must satisfy minimum <= expected <= maximum");
        }
        if self
            .remaining
            .is_some_and(|remaining| remaining > self.maximum)
        {
            return Err("remaining duration cannot exceed maximum");
        }
        Ok(())
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum EstimateSource {
    User,
    Learned,
    Ai,
    Imported,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct Priority {
    /// A user-facing value in the inclusive range 0..=10.
    pub importance: u8,
    /// A user-facing value in the inclusive range 0..=10.
    pub urgency: u8,
}

impl Priority {
    pub const NONE: Self = Self {
        importance: 0,
        urgency: 0,
    };

    #[must_use]
    pub const fn score(self) -> u16 {
        self.importance as u16 * self.urgency as u16
    }

    pub(crate) fn validate(self) -> Result<(), &'static str> {
        if self.importance > 10 || self.urgency > 10 {
            return Err("priority importance and urgency must be in 0..=10");
        }
        Ok(())
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum WorkStatus {
    NotStarted,
    Scheduled,
    Active,
    Paused,
    Completed,
    Skipped,
    Canceled,
    Blocked,
}

impl WorkStatus {
    #[must_use]
    pub const fn is_terminal(self) -> bool {
        matches!(self, Self::Completed | Self::Skipped | Self::Canceled)
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ItemKind {
    Task,
    RecurringTask(RecurringTaskSpec),
    Habit(HabitSpec),
    Routine(RoutineSpec),
    Goal(GoalSpec),
    Break(BreakSpec),
    CalendarEvent(CalendarEventSpec),
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct RecurringTaskSpec {
    pub recurrence: Recurrence,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct HabitSpec {
    pub recurrence: Recurrence,
    pub target: Option<QuantityTarget>,
    pub preserves_streak_when_paused: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct RoutineSpec {
    /// When true, children run in ascending `sibling_order`.
    pub ordered: bool,
    pub recurrence: Option<Recurrence>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct GoalSpec {
    pub measures: Vec<GoalMeasure>,
    pub weekly_allocation: Option<AllocationRange>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct GoalMeasure {
    pub name: String,
    pub target: i64,
    pub current: i64,
    pub unit: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct AllocationRange {
    pub minimum: Minutes,
    pub maximum: Option<Minutes>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct BreakSpec {
    pub category: BreakCategory,
    pub mandatory: bool,
    pub prompt_to_resume: bool,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum BreakCategory {
    Rest,
    Meal,
    Movement,
    Pomodoro,
    Decompression,
    Other,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CalendarEventSpec {
    pub start: OffsetDateTime,
    pub end: OffsetDateTime,
    pub immutable: bool,
    pub all_day: bool,
    pub source_calendar_id: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct QuantityTarget {
    pub amount: u32,
    pub unit: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum Recurrence {
    Daily {
        times_per_day: u16,
    },
    Weekly {
        times_per_week: u16,
        weekdays: BTreeSet<DayOfWeek>,
    },
    Monthly {
        times_per_month: u16,
    },
    EveryInterval {
        interval: Minutes,
    },
    AfterCompletion {
        interval: Minutes,
    },
    /// General frequency form used when calendar-vs-rolling semantics and
    /// minimum spacing must be explicit.
    Frequency {
        target: u16,
        period: RecurrencePeriod,
        semantics: RecurrenceSemantics,
        #[serde(default)]
        weekdays: BTreeSet<DayOfWeek>,
        #[serde(default)]
        minimum_spacing: Minutes,
        #[serde(default)]
        anchor: Option<OffsetDateTime>,
    },
    Custom {
        /// RFC 5545 recurrence rule, retained losslessly for calendar parity.
        rrule: String,
    },
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RecurrencePeriod {
    Day,
    Week,
    Month,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RecurrenceSemantics {
    /// Counts reset at local day, week, or month boundaries.
    Calendar,
    /// Counts use intervals anchored to creation, completion, or an override.
    Rolling,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct WorkItem {
    pub id: ItemId,
    /// Monotonic entity revision used by offline sync conflict handling.
    pub revision: u64,
    pub title: String,
    pub kind: ItemKind,
    pub status: WorkStatus,
    pub parent_id: Option<ItemId>,
    pub sibling_order: Option<u32>,
    /// Lets a parent reserve independent work in addition to rolled-up children.
    pub has_own_effort: bool,
    pub goal_ids: BTreeSet<ItemId>,
    pub priority: Priority,
    pub duration: Option<DurationEstimate>,
    pub constraints: SchedulingConstraints,
    pub split_policy: SplitPolicy,
    pub energy: Option<Qualified<EnergyLevel>>,
    pub tags: BTreeSet<String>,
    pub created_at: OffsetDateTime,
    pub updated_at: OffsetDateTime,
}

impl WorkItem {
    /// Calendar events always occupy time. Other parents roll their child work
    /// up and occupy no time unless they explicitly carry independent effort.
    #[must_use]
    pub fn occupies_time(&self, has_children: bool) -> bool {
        match self.kind {
            ItemKind::CalendarEvent(_) => true,
            // Goals and routines are semantic containers even before their
            // first child is created.
            ItemKind::Goal(_) | ItemKind::Routine(_) => self.has_own_effort,
            _ => !has_children || self.has_own_effort,
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum EnergyLevel {
    Low,
    Medium,
    Deep,
}

impl EnergyLevel {
    const fn rank(self) -> u8 {
        match self {
            Self::Low => 0,
            Self::Medium => 1,
            Self::Deep => 2,
        }
    }

    #[must_use]
    pub(crate) const fn satisfies(self, required: Self) -> bool {
        self.rank() >= required.rank()
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "level", rename_all = "snake_case")]
pub enum ConstraintStrength {
    Hard,
    Soft { weight: u32 },
}

impl ConstraintStrength {
    pub const DEFAULT_SOFT: Self = Self::Soft { weight: 100 };

    #[must_use]
    pub const fn is_hard(self) -> bool {
        matches!(self, Self::Hard)
    }

    #[must_use]
    pub const fn weight(self) -> u32 {
        match self {
            Self::Hard => 0,
            Self::Soft { weight } => weight,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Qualified<T> {
    pub value: T,
    pub strength: ConstraintStrength,
}

impl<T> Qualified<T> {
    #[must_use]
    pub const fn hard(value: T) -> Self {
        Self {
            value,
            strength: ConstraintStrength::Hard,
        }
    }

    #[must_use]
    pub const fn soft(value: T, weight: u32) -> Self {
        Self {
            value,
            strength: ConstraintStrength::Soft { weight },
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Default)]
pub struct SchedulingConstraints {
    pub earliest_start: Option<Qualified<OffsetDateTime>>,
    pub latest_finish: Option<Qualified<OffsetDateTime>>,
    pub minimum_notice: Option<Qualified<Minutes>>,
    pub allowed_weekdays: Option<Qualified<BTreeSet<DayOfWeek>>>,
    pub preferred_daily_windows: Vec<Qualified<DailyTimeWindow>>,
    pub preferred_absolute_windows: Vec<Qualified<AbsoluteWindow>>,
    pub forbidden_windows: Vec<Qualified<AbsoluteWindow>>,
    pub required_contexts: Vec<Qualified<String>>,
    pub required_location: Option<Qualified<String>>,
    pub dependencies: Vec<Dependency>,
    pub maximum_daily_work: Option<Qualified<Minutes>>,
    pub maximum_weekly_work: Option<Qualified<Minutes>>,
    pub buffers: BufferPolicy,
    /// A system-generated hard window for one materialized recurrence. It is
    /// independent from user-authored earliest/latest preferences.
    #[serde(default)]
    pub occurrence_window: Option<AbsoluteWindow>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
pub struct BufferPolicy {
    pub before: Minutes,
    pub after: Minutes,
    /// Hard buffers reserve time. Soft buffers may be compressed with a visible
    /// plan violation and penalty.
    pub strength: Option<ConstraintStrength>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct AbsoluteWindow {
    pub start: OffsetDateTime,
    pub end: OffsetDateTime,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct DailyTimeWindow {
    pub weekdays: BTreeSet<DayOfWeek>,
    /// Inclusive minute since local midnight, 0..=1439.
    pub start_minute: u16,
    /// Exclusive minute since local midnight, 1..=1440. A value lower than
    /// `start_minute` denotes a window crossing midnight.
    pub end_minute: u16,
}

impl DailyTimeWindow {
    #[must_use]
    pub fn contains(&self, start: OffsetDateTime, end: OffsetDateTime) -> bool {
        let weekday = DayOfWeek::from_time(start.weekday());
        if !self.weekdays.is_empty() && !self.weekdays.contains(&weekday) {
            return false;
        }
        let start_minute = u16::from(start.hour()) * 60 + u16::from(start.minute());
        let end_minute = u16::from(end.hour()) * 60 + u16::from(end.minute());
        if self.start_minute < self.end_minute {
            start_minute >= self.start_minute
                && (end.date() == start.date())
                && end_minute <= self.end_minute
        } else {
            // Crossing-midnight window, for example 22:00–02:00.
            start_minute >= self.start_minute || end_minute <= self.end_minute
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum DayOfWeek {
    Monday,
    Tuesday,
    Wednesday,
    Thursday,
    Friday,
    Saturday,
    Sunday,
}

impl DayOfWeek {
    pub(crate) const fn from_time(value: time::Weekday) -> Self {
        match value {
            time::Weekday::Monday => Self::Monday,
            time::Weekday::Tuesday => Self::Tuesday,
            time::Weekday::Wednesday => Self::Wednesday,
            time::Weekday::Thursday => Self::Thursday,
            time::Weekday::Friday => Self::Friday,
            time::Weekday::Saturday => Self::Saturday,
            time::Weekday::Sunday => Self::Sunday,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Dependency {
    pub item_id: ItemId,
    pub relation: DependencyRelation,
    pub minimum_lag: Minutes,
    pub strength: ConstraintStrength,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum DependencyRelation {
    FinishToStart,
    StartToStart,
    FinishToFinish,
    StartToFinish,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum SplitPolicy {
    #[default]
    Indivisible,
    Splittable {
        minimum_session: Minutes,
        maximum_session: Minutes,
        maximum_sessions: u16,
        minimum_gap: Minutes,
        maximum_days: Option<u16>,
    },
}

impl SplitPolicy {
    pub(crate) fn validate(&self) -> Result<(), &'static str> {
        if let Self::Splittable {
            minimum_session,
            maximum_session,
            maximum_sessions,
            ..
        } = self
        {
            if minimum_session.is_zero() {
                return Err("minimum session must be greater than zero");
            }
            if minimum_session > maximum_session {
                return Err("minimum session cannot exceed maximum session");
            }
            if *maximum_sessions == 0 {
                return Err("maximum sessions must be greater than zero");
            }
        }
        Ok(())
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AvailabilityWindow {
    pub start: OffsetDateTime,
    pub end: OffsetDateTime,
    pub contexts: BTreeSet<String>,
    pub location: Option<String>,
    pub energy: EnergyLevel,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct FixedBlock {
    pub id: Uuid,
    pub title: String,
    pub start: OffsetDateTime,
    pub end: OffsetDateTime,
    pub source: FixedBlockSource,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum FixedBlockSource {
    GoogleCalendar,
    Sleep,
    ProtectedTime,
    Travel,
    Manual,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PreviousAssignment {
    pub item_id: ItemId,
    #[serde(default)]
    pub occurrence_id: Option<OccurrenceId>,
    pub blocks: Vec<PreviousBlock>,
    /// Pinned blocks are immutable inputs. Unpinned blocks are stability hints.
    pub pinned: bool,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct PreviousBlock {
    pub start: OffsetDateTime,
    pub end: OffsetDateTime,
    pub session_index: u16,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct SchedulerConfig {
    pub slot_granularity: Minutes,
    pub stability_weight: u32,
    pub default_soft_weight: u32,
}

impl Default for SchedulerConfig {
    fn default() -> Self {
        Self {
            slot_granularity: Minutes(5),
            stability_weight: 4,
            default_soft_weight: 100,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PlanRequest {
    /// Explicit clock input; the engine never reads the wall clock.
    pub as_of: OffsetDateTime,
    pub horizon_start: OffsetDateTime,
    pub horizon_end: OffsetDateTime,
    pub items: Vec<WorkItem>,
    pub availability: Vec<AvailabilityWindow>,
    pub fixed_blocks: Vec<FixedBlock>,
    pub previous_assignments: Vec<PreviousAssignment>,
    pub config: SchedulerConfig,
    /// Defaults preserve compatibility with requests written before recurrence
    /// materialization was introduced.
    #[serde(default)]
    pub recurrence_context: RecurrenceContext,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Default)]
pub struct RecurrenceContext {
    /// Platform-resolved local days. Supplying these makes IANA timezone and
    /// DST intent explicit without embedding a timezone database in the core.
    #[serde(default)]
    pub calendar: RecurrenceCalendar,
    /// Last completion is the rolling anchor for `after_completion` rules.
    #[serde(default)]
    pub completion_anchors: BTreeMap<ItemId, OffsetDateTime>,
    /// Optional anchor override for rolling frequency and interval rules.
    #[serde(default)]
    pub rolling_anchors: BTreeMap<ItemId, OffsetDateTime>,
    /// Per-series spacing override, including legacy recurrence forms.
    #[serde(default)]
    pub minimum_spacing: BTreeMap<ItemId, Minutes>,
    /// Stable IDs already satisfied in the current recurrence cycle. They stay
    /// visible in expansion output but do not create schedule demand.
    #[serde(default)]
    pub completed_occurrence_ids: BTreeSet<OccurrenceId>,
    #[serde(default)]
    pub pauses: Vec<RecurrencePause>,
    #[serde(default)]
    pub exceptions: Vec<RecurrenceException>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct RecurrenceCalendar {
    /// IANA identifier recorded for audit/display; day boundaries below are
    /// authoritative for calculations.
    pub time_zone_id: Option<String>,
    pub week_starts_on: DayOfWeek,
    pub days: Vec<ZonedDayBoundary>,
}

impl Default for RecurrenceCalendar {
    fn default() -> Self {
        Self {
            time_zone_id: None,
            week_starts_on: DayOfWeek::Monday,
            days: Vec::new(),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct ZonedDayBoundary {
    pub local_date: time::Date,
    /// Instant corresponding to local 00:00 at the start of the day.
    pub start: OffsetDateTime,
    /// Instant corresponding to the next local 00:00. A DST day may therefore
    /// contain 23 or 25 elapsed hours.
    pub end: OffsetDateTime,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct RecurrencePause {
    pub item_id: ItemId,
    pub start: OffsetDateTime,
    pub end: OffsetDateTime,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct RecurrenceException {
    pub item_id: ItemId,
    pub selector: RecurrenceExceptionSelector,
    pub action: RecurrenceExceptionAction,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum RecurrenceExceptionSelector {
    Occurrence { id: OccurrenceId },
    LocalDate { date: time::Date },
    NominalStart { at: OffsetDateTime },
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum RecurrenceExceptionAction {
    Skip,
    Move {
        start: OffsetDateTime,
        end: OffsetDateTime,
    },
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct OccurrenceId(pub Uuid);

impl std::fmt::Display for OccurrenceId {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.0.fmt(formatter)
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct Occurrence {
    pub id: OccurrenceId,
    pub series_item_id: ItemId,
    pub nominal_start: OffsetDateTime,
    pub nominal_end: OffsetDateTime,
    pub window_start: OffsetDateTime,
    pub window_end: OffsetDateTime,
    pub local_date: Option<time::Date>,
    pub ordinal: u32,
    pub state: OccurrenceState,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum OccurrenceState {
    Generated,
    Completed,
    Paused,
    Skipped,
}

#[derive(Debug, Error, Clone, PartialEq, Eq)]
pub enum HierarchyError {
    #[error("duplicate item id {0}")]
    DuplicateItem(ItemId),
    #[error("item {item} references missing parent {parent}")]
    MissingParent { item: ItemId, parent: ItemId },
    #[error("hierarchy cycle includes item {0}")]
    Cycle(ItemId),
}

/// Calculates expected duration for every parent without scheduling parents as
/// extra work. A parent's own estimate is included only when `has_own_effort`
/// is true; a leaf always includes its own estimate.
///
/// # Errors
///
/// Returns an error when IDs are duplicated, a parent is missing, or the
/// hierarchy contains a cycle.
pub fn roll_up_expected_durations(
    items: &[WorkItem],
) -> Result<BTreeMap<ItemId, Minutes>, HierarchyError> {
    let by_id: BTreeMap<_, _> = items.iter().map(|item| (item.id, item)).collect();
    if by_id.len() != items.len() {
        let mut seen = BTreeSet::new();
        if let Some(duplicate) = items
            .iter()
            .map(|item| item.id)
            .find(|id| !seen.insert(*id))
        {
            return Err(HierarchyError::DuplicateItem(duplicate));
        }
    }

    let mut children: BTreeMap<ItemId, Vec<ItemId>> = BTreeMap::new();
    for item in items {
        if let Some(parent) = item.parent_id {
            if !by_id.contains_key(&parent) {
                return Err(HierarchyError::MissingParent {
                    item: item.id,
                    parent,
                });
            }
            children.entry(parent).or_default().push(item.id);
        }
    }

    let mut result = BTreeMap::new();
    for id in by_id.keys() {
        let mut visiting = BTreeSet::new();
        visit_rollup(*id, &by_id, &children, &mut visiting, &mut result)?;
    }
    Ok(result)
}

fn visit_rollup(
    id: ItemId,
    by_id: &BTreeMap<ItemId, &WorkItem>,
    children: &BTreeMap<ItemId, Vec<ItemId>>,
    visiting: &mut BTreeSet<ItemId>,
    result: &mut BTreeMap<ItemId, Minutes>,
) -> Result<u32, HierarchyError> {
    if let Some(value) = result.get(&id) {
        return Ok(value.get());
    }
    if !visiting.insert(id) {
        return Err(HierarchyError::Cycle(id));
    }

    let item = by_id[&id];
    let child_ids = children.get(&id).map_or(&[][..], Vec::as_slice);
    let mut total = 0_u32;
    if child_ids.is_empty() || item.has_own_effort {
        total = item
            .duration
            .map_or(0, |duration| duration.planning_minutes().get());
    }
    for child in child_ids {
        total = total.saturating_add(visit_rollup(*child, by_id, children, visiting, result)?);
    }
    visiting.remove(&id);
    result.insert(id, Minutes(total));
    Ok(total)
}
